apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-api
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-api
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.global.registry }}/{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Values.global.imageTag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgres:5432/{{ .Values.postgresql.auth.database }}
            - name: REDIS_HOST
              value: "{{ .Release.Name }}-valkey"
            - name: SECRET_KEY
              value: {{ .Values.api.env.SECRET_KEY }}
            - name: EMAIL_MODE
              value: {{ .Values.api.env.EMAIL_MODE }}
            - name: FROM_EMAIL
              value: {{ .Values.api.env.FROM_EMAIL }}
            - name: FROM_NAME
              value: {{ .Values.api.env.FROM_NAME }}
            - name: MAILGUN_API_KEY
              value: {{ .Values.api.env.MAILGUN_API_KEY }}
            - name: MAILGUN_DOMAIN
              value: {{ .Values.api.env.MAILGUN_DOMAIN }}
            - name: MAILGUN_REGION
              value: {{ .Values.api.env.MAILGUN_REGION }}
            - name: WEBSITE_ADDRESS
              value: {{ .Values.api.env.WEBSITE_ADDRESS }}
            - name: API_ADDRESS
              value: {{ .Values.api.env.API_ADDRESS }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}