apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrations
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-migrations
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-migrations
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-postgres
          image: "postgres:{{ .Values.postgresql.image.tag }}"
          command: ['sh', '-c', 'until pg_isready -h {{ .Release.Name }}-postgres -p 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
        - name: migrations
          image: "{{ .Values.global.registry }}/{{ .Values.migrations.image.repository }}:{{ .Values.migrations.image.tag | default .Values.global.imageTag }}"
          command: ["alembic", "upgrade", "head"]
          env:
            - name: DATABASE_URL
              value: postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgres:5432/{{ .Values.postgresql.auth.database }}
