apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-service
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-service
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-service
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: service
          image: "{{ .Values.global.registry }}/{{ .Values.service.image.repository }}:{{ .Values.service.image.tag | default .Values.global.imageTag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              value: postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgres:5432/{{ .Values.postgresql.auth.database }}
            - name: REDIS_HOST
              value: "{{ .Release.Name }}-valkey"
