apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ux
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-ux
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-ux
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-ux
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: ux
          image: "{{ .Values.global.registry }}/{{ .Values.ux.image.repository }}:{{ .Values.ux.image.tag | default .Values.global.imageTag }}"
          imagePullPolicy: Always 
          ports:
            - name: http
              containerPort: 80 
              protocol: TCP
          env:
            - name: VITE_API_MODE
              value: {{ .Values.ux.env.VITE_API_MODE }}
            - name: VITE_API_URL
              value: {{ .Values.ux.env.VITE_API_URL }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ux
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-ux
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.ux.service.type }}
  ports:
    - port: {{ .Values.ux.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-ux
    app.kubernetes.io/instance: {{ .Release.Name }}
